## Site Meta ##
baseurl: "/Bruno.Durieu.github.io"
title: "Bruno Durieu"
# The description of the website
description: "Photographies de Bruno Durieu"
# Keywords/tags for you site.
keywords: "photographie, oiseaux, nature, photography, blog, photography-blog, photo-blog, photographie-de-rue"
# Your copyright message.
copyright: "Copyright &copy; 2026 - Bruno Durieu."

## Site Configurations ##
# 1st heading of the site.
header: "Bruno Durieu"
# 2nd heading/sub heading of the website.
subheader: "Photographies"
# A description/bio of the website.
bio: "J’aime capturer ce qui ne se répète jamais  un instant, une lumière, une émotion, une scène de vie. 
Sculpteur de lumière, je cherche à façonner chaque image en jouant avec les ombres, les contrastes et les lumières naturelles, pour révéler toute la beauté d’un instant. 
La nature occupe une place particulière dans mon univers. J’aime y explorer les paysages, observer la vie animale et immortaliser ces moments fugaces où la nature dévoile toute sa force et sa poésie. 
Curieux de nature et profondément attiré par le vivant, je suis un photographe pluridisciplinaire qui aime expérimenter, découvrir et toucher à différents univers. 
Chaque sortie est une nouvelle aventure, chaque rencontre une occasion de raconter une histoire à travers mes images.
Explorer, observer, ressentir et transmettre.
C’est cette sensibilité à la nature et au vivant que je cherche à partager dans chacune de mes photographies.

Bienvenue dans mon univers…  
Bonne visite !"
social:
  # Your Twitter username.
  twitter_username: ""
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.
  instagram_username: ""
  # GitHub username.
  github_username: ""
  # Your email address.
  email: "bruno.durieu@gmail.com"

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true
plugins:
  - jekyll-resize
include:
  - cache   